#!/usr/bin/env python3
"""Build shared WOFF2 fonts without changing Urdu outlines or shaping rules.

Requires fonttools[woff]. Run from any directory. Source downloads are pinned
to the reviewed Google Fonts CSS2 snapshot, not a moving font release.
"""
import hashlib
import json
from pathlib import Path
import re
from urllib.request import urlopen

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
OUT = ROOT / 'public/fonts'
CACHE = ROOT / 'tmp/font-sources'
SOURCE = (HERE / 'google-fonts-source.css').read_text()
ARABIC = 'https://fonts.gstatic.com/s/notonastaliqurdu/v23/LhW4MUPbN-oZdNFcBy1-DJYsEoTq5pu3SvoMGdX1OW12.woff2'
LATIN = 'https://fonts.gstatic.com/s/notonastaliqurdu/v23/LhW4MUPbN-oZdNFcBy1-DJYsEoTq5pu3T_oMGdX1OQ.woff2'
INTER = 'https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2'


def source(url):
    path = CACHE / url.rsplit('/', 1)[1]
    if not path.exists():
        with urlopen(url, timeout=30) as response:
            path.write_bytes(response.read())
    return path


def emit(name, font):
    temp = CACHE / (name + '.woff2')
    font.flavor = 'woff2'
    font.save(temp)
    content = temp.read_bytes()
    digest = hashlib.sha256(content).hexdigest()[:12]
    path = OUT / f'{name}-{digest}.woff2'
    path.write_bytes(content)
    return '/fonts/' + path.name, len(content)


OUT.mkdir(parents=True, exist_ok=True)
CACHE.mkdir(parents=True, exist_ok=True)
(CACHE / '.gitignore').write_text('*\n')
arabic_source = source(ARABIC)
font = TTFont(arabic_source, recalcTimestamp=False)
# Include the complete basic Arabic block, join controls, punctuation, NBSP,
# and the salutation present in one legacy article. Never subset per headline.
coverage = set(range(0x600, 0x700)) | {0x20, 0xA0, 0x200C, 0x200D, 0x200E, 0x2010, 0x2011, 0xFDFA}
options = subset.Options()
options.layout_features = ['*']
options.retain_gids = True  # Allows an exact HarfBuzz glyph/position comparison.
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes=coverage)
subsetter.subset(font)
arabic_url, arabic_bytes = emit('noto-nastaliq-urdu-basic-v23', font)
# TTF files are QA inputs only; never deployed.
font.flavor = None
font.save(CACHE / 'urdu-basic.ttf')
original = TTFont(arabic_source, recalcTimestamp=False)
original.flavor = None
original.save(CACHE / 'urdu-original.ttf')

inter_source = source(INTER)
inter = instantiateVariableFont(TTFont(inter_source, recalcTimestamp=False), {'wght': (700, 800)}, inplace=True)
inter_url, inter_bytes = emit('inter-latin-700-800-v20', inter)
latin_source = source(LATIN)
latin_url, latin_bytes = emit('noto-nastaliq-latin-v23', TTFont(latin_source, recalcTimestamp=False))

# The original Arabic face remains a fallback for rare characters. The later
# face wins only within the explicit covered range. All other scripts remain.
css = SOURCE.replace(INTER, inter_url).replace(LATIN, latin_url)
css += f'''
/* Shared Urdu/Arabic subset; see scripts/fonts/README.md. */
@font-face {{
  font-family: 'Noto Nastaliq Urdu';
  font-style: normal;
  font-weight: 400 700;
  font-display: swap;
  src: url({arabic_url}) format('woff2');
  unicode-range: U+0020, U+00A0, U+0600-06FF, U+200C-200E, U+2010-2011, U+FDFA;
}}
'''
(ROOT / 'src/styles/google-fonts.css').write_text('/* Generated by scripts/fonts/build.py. */\n' + css)

base = ROOT / 'src/layouts/Base.astro'
text = base.read_text()
text, replacements = re.subn(r'(<link rel="preload" as="font" type="font/woff2" crossorigin href=")[^"]+(" />)',
                             lambda match: match[1] + arabic_url + match[2], text)
assert replacements == 1, 'Expected exactly one shared Urdu font preload'
text = text.replace('    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n', '')
base.write_text(text)
for license_name in ('Noto-OFL.txt', 'Inter-OFL.txt'):
    (OUT / license_name).write_bytes((HERE / license_name).read_bytes())

manifest = {
    'arabic': {'url': arabic_url, 'bytes': arabic_bytes, 'source': ARABIC, 'source_bytes': arabic_source.stat().st_size},
    'inter': {'url': inter_url, 'bytes': inter_bytes, 'source': INTER, 'source_bytes': inter_source.stat().st_size},
    'latin': {'url': latin_url, 'bytes': latin_bytes, 'source': LATIN, 'source_bytes': latin_source.stat().st_size},
}
(HERE / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(json.dumps(manifest, indent=2), flush=True)
