export function spec(origin) {
 const resource={type:'object',required:['id','type','title','description','url','language','topics'],properties:{id:{type:'string'},type:{type:'string',enum:['guides','how-to','prompts','learn','courses']},title:{type:'string'},description:{type:'string'},url:{type:'string',format:'uri'},language:{type:'string',enum:['ur']},topics:{type:'array',items:{type:'string'}},level:{type:['string','null']},published_at:{type:['string','null'],format:'date-time'},updated_at:{type:['string','null'],format:'date-time'},last_verified:{type:['string','null'],format:'date-time'},availability:{type:'string'},price:{type:'number'},price_currency:{type:'string'}}};
 const error={description:'Request error',content:{'application/json':{schema:{type:'object',properties:{error:{type:'object',properties:{code:{type:'string'},message:{type:'string'}}}}}}}};
 const response=schema=>({description:'Successful response',content:{'application/json':{schema}}});
 const list={type:'object',properties:{resources:{type:'array',items:resource},total:{type:'integer'},limit:{type:'integer'},offset:{type:'integer'},next_offset:{type:['integer','null']},catalogue_generated_at:{type:'string',format:'date-time'}}};
 const params=[{name:'q',in:'query',description:'Space-separated keywords; all must match. Urdu and English supported. Not semantic search. Try ChatGPT or پرامٹ.',schema:{type:'string',maxLength:200}},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:10}},{name:'offset',in:'query',schema:{type:'integer',minimum:0,maximum:100000,default:0}}];
 return {openapi:'3.1.0',info:{title:'Urdu AI Learning API',version:'1.0.0',description:'Read-only discovery of published Urdu AI educational resource metadata. Return source links to learners. No authentication or payments. Catalogue is a deployment snapshot; see catalogue_generated_at.',contact:{name:'Urdu AI',email:'ai@urduai.org',url:'https://urduai.org/contact/'},termsOfService:'https://urduai.org/terms/'},servers:[{url:origin}],security:[],paths:{
 '/v1/resources':{get:{operationId:'searchLearningResources',summary:'Find Urdu AI learning resources',parameters:[...params,{name:'type',in:'query',schema:resource.properties.type}],responses:{200:response(list),400:error}}},
 '/v1/resource':{get:{operationId:'getLearningResource',summary:'Get metadata and source link for one resource',parameters:[{name:'id',in:'query',required:true,schema:{type:'string'},example:'courses/masterclass'}],responses:{200:response({type:'object',properties:{resource,catalogue_generated_at:{type:'string'}}}),400:error,404:error}}},
 '/v1/courses':{get:{operationId:'findCourses',summary:'Find available free course metadata',parameters:params,responses:{200:response(list),400:error}}},
 '/health':{get:{operationId:'getApiHealth',summary:'API status and catalogue freshness',responses:{200:response({type:'object',properties:{status:{type:'string'},version:{type:'string'},resource_count:{type:'integer'},catalogue_generated_at:{type:'string'}}})}}}}};
}
